"""
STUDENT TEMPLATE - models/sentiment_analyzer.py
Sentiment analysis of financial news headlines using a VADER-like
lexicon approach.  The VADER_LEXICON dictionary (~2000 words with
sentiment scores) is provided — your job is to implement the scoring logic.
"""

import re
import math
from typing import Optional
from .. import data_client as dc

VADER_LEXICON: dict[str, float] = {
    "abandon": -2.0, "abandoned": -2.0, "abandons": -2.0, "absorb": 1.0, "absorbed": 1.0,
    "accept": 1.5, "accepted": 1.5, "accepting": 1.5, "accepts": 1.5, "access": 1.0,
    "accident": -2.0, "accidental": -2.0, "accidentally": -2.0, "accomplish": 2.0,
    "accomplished": 2.0, "accomplishes": 2.0, "accountability": 1.0, "accountable": 1.0,
    "accurate": 1.5, "accuse": -1.5, "accused": -1.5, "accuses": -1.5, "achievable": 1.5,
    "achieve": 2.0, "achieved": 2.0, "achieves": 2.0, "achievement": 2.0, "acid": -1.5,
    "acknowledge": 1.0, "acknowledged": 1.0, "acquisition": 0.5, "active": 1.0,
    "activist": 0.5, "addict": -2.0, "addicted": -2.0, "addiction": -2.0, "adept": 1.5,
    "adeptly": 1.5, "adequate": 1.0, "adjust": 0.5, "adjusted": 0.5, "admirable": 2.0,
    "admirably": 2.0, "admire": 2.0, "admired": 2.0, "admit": -1.0, "admitted": -1.0,
    "admittedly": -1.0, "admonish": -2.0, "admonished": -2.0, "adopt": 1.0, "adopted": 1.0,
    "advance": 1.5, "advanced": 1.5, "advancement": 1.5, "advancements": 1.5, "advances": 1.5,
    "advantage": 1.5, "advantageous": 2.0, "adversarial": -1.5, "adversary": -1.5,
    "adverse": -2.0, "adversity": -2.0, "advocate": 1.5, "advocated": 1.5, "advocates": 1.5,
    "afford": 1.5, "affordable": 2.0, "affordably": 2.0, "afraid": -1.5, "aggravate": -2.0,
    "aggravated": -2.0, "aggravates": -2.0, "aggressive": -1.5, "aggressively": -1.5,
    "aggressor": -2.0, "agile": 1.5, "agility": 1.5, "agitate": -2.0, "agitated": -2.0,
    "agitates": -2.0, "agitation": -2.0, "agony": -2.5, "agree": 1.5, "agreeable": 1.5,
    "agreed": 1.5, "agreement": 1.5, "agrees": 1.5, "alarm": -1.5, "alarmed": -1.5,
    "alarming": -2.0, "alarmingly": -2.0, "alerts": -0.5, "alienate": -2.0,
    "alienated": -2.0, "alive": 2.0, "alliance": 1.5, "alliances": 1.5, "allow": 1.0,
    "allowing": 1.0, "allows": 1.0, "alone": -1.0, "altruist": 2.0, "altruistic": 2.0,
    "amaze": 2.5, "amazed": 2.5, "amazes": 2.5, "amazing": 3.0, "amazingly": 3.0,
    "ambitious": 2.0, "amend": 1.0, "amended": 1.0, "amplify": 1.0, "amuse": 1.5,
    "amused": 1.5, "amusement": 1.5, "amusements": 1.5, "anger": -2.5, "angers": -2.5,
    "angry": -2.5, "anguish": -2.5, "animosity": -2.0, "annoy": -2.0, "annoyance": -2.0,
    "annoyed": -2.0, "annoying": -2.0, "annually": 0.5, "anomaly": -1.0, "anxiety": -2.0,
    "anxious": -1.5, "apathetic": -2.0, "apathy": -2.5, "apes": -1.0, "apocalyptic": -2.5,
    "apologise": -1.5, "apologize": -1.5, "apology": -1.5, "appal": -2.5, "appall": -2.5,
    "appalled": -2.5, "appalling": -2.5, "apparently": -0.5, "appeal": 1.5, "appealing": 1.5,
    "applaud": 2.0, "applauded": 2.0, "applauding": 2.0, "applause": 2.0, "appreciate": 1.5,
    "appreciated": 1.5, "appreciates": 1.5, "appreciation": 1.5, "appreciative": 1.5,
    "approve": 1.5, "approved": 1.5, "approves": 1.5, "ardent": 1.5, "arguable": -0.5,
    "arguably": -0.5, "argue": -1.5, "argued": -1.5, "argues": -1.5, "argument": -1.5,
    "arrest": -2.5, "arrested": -2.5, "arrests": -2.5, "artificial": -0.5, "ascend": 1.5,
    "ascendant": 1.5, "ashamed": -2.0, "aspiration": 1.5, "aspirations": 1.5, "aspire": 1.5,
    "aspiring": 1.5, "assault": -2.5, "assaults": -2.5, "assure": 1.5, "assured": 1.5,
    "assures": 1.5, "astonish": 2.5, "astonished": 2.5, "astonishing": 2.5,
    "astonishingly": 2.5, "astound": 2.5, "astounded": 2.5, "astounding": 2.5,
    "astoundingly": 2.5, "atrocious": -3.0, "atrocities": -3.0, "atrophy": -2.0,
    "attack": -2.0, "attacked": -2.0, "attacks": -2.0, "attract": 1.5, "attracted": 1.5,
    "attracting": 1.5, "attraction": 1.5, "attractions": 1.5, "attractive": 1.5,
    "attractively": 1.5, "attune": 1.0, "attuned": 1.0, "audacious": 1.5,
    "audaciously": 1.5, "audacity": 1.5, "auspicious": 2.5, "authoritarian": -2.0,
    "authority": 0.5, "autonomous": 1.0, "available": 1.0, "average": -0.5, "avid": 1.5,
    "avoid": -1.0, "avoided": -1.0, "avoids": -1.0, "award": 2.0, "awarded": 2.0,
    "awards": 2.0, "awesome": 3.0, "awful": -2.5, "awkward": -1.5, "backed": 1.0,
    "backing": 1.0, "backs": 1.0, "bad": -2.5, "bail": -1.5, "bailed": -1.5,
    "bailout": -1.5, "balanced": 1.0, "bamboo": 0.5, "ban": -2.0, "banned": -2.0,
    "bankrupt": -2.5, "bankruptcy": -2.5, "banned": -2.0, "barrier": -1.5,
    "barriers": -1.5, "battle": -1.5, "battled": -1.5, "battles": -1.5, "beaten": -2.0,
    "beat": 1.5, "beating": -1.0, "beautiful": 2.5, "beautifully": 2.5, "beauty": 2.0,
    "beef": -1.0, "beefed": -1.0, "befriend": 1.5, "beg": -1.5, "beggar": -2.0,
    "beggars": -2.0, "beginner": 0.5, "belittle": -2.0, "belittled": -2.0, "beloved": 2.0,
    "beneficial": 2.0, "beneficially": 2.0, "beneficiary": 1.5, "benefit": 1.5,
    "benefits": 1.5, "benevolent": 2.0, "bereave": -2.5, "bereaved": -2.5,
    "bereavement": -2.5, "berate": -2.5, "berated": -2.5, "best": 3.0, "betray": -3.0,
    "betrayal": -3.0, "betrayed": -3.0, "betraying": -3.0, "betrays": -3.0,
    "better": 2.0, "bias": -1.0, "biased": -1.0, "big": 1.0, "biting": -1.5,
    "bitten": -1.5, "blah": -0.5, "blame": -2.0, "blamed": -2.0, "blames": -2.0,
    "blaming": -2.0, "bless": 2.0, "blesses": 2.0, "blessing": 2.0, "blight": -2.0,
    "blind": -1.5, "bliss": 2.5, "blissful": 2.5, "blistering": -2.0, "bloat": -1.5,
    "bloated": -1.5, "block": -1.5, "blocked": -1.5, "blocking": -1.5, "blocks": -1.5,
    "bloom": 1.5, "blossom": 1.5, "blunder": -2.0, "blundering": -2.0, "blunders": -2.0,
    "boast": 1.5, "boasted": 1.5, "boastful": 1.5, "boasting": 1.5, "bold": 1.5,
    "boldly": 1.5, "boldness": 1.5, "bolster": 1.5, "bolstered": 1.5, "boost": 1.5,
    "boosted": 1.5, "boosting": 1.5, "boosts": 1.5, "bore": -1.5, "bored": -1.5,
    "boredom": -2.0, "boring": -1.5, "botch": -2.5, "botched": -2.5, "bother": -2.0,
    "bothered": -2.0, "bothers": -2.0, "bottom": -1.5, "boycott": -2.0,
    "boycotted": -2.0, "boycotting": -2.0, "boycotts": -2.0, "brain": 1.0,
    "brainchild": 1.5, "brainstorm": 1.0, "brave": 2.0, "bravely": 2.0,
    "bravery": 2.0, "breakthrough": 2.0, "breakthroughs": 2.0, "breach": -2.0,
    "breached": -2.0, "breaches": -2.0, "bribe": -2.5, "bribed": -2.5, "bribes": -2.5,
    "bright": 2.0, "brighten": 1.5, "brightened": 1.5, "brightening": 1.5,
    "brighter": 2.0, "brightest": 2.5, "brilliance": 2.5, "brilliant": 3.0,
    "brilliantly": 3.0, "brink": -1.0, "brisk": 1.0, "broke": -2.0, "broken": -2.0,
    "broker": 0.0, "bruise": -2.0, "bruised": -2.0, "bruises": -2.0, "brutal": -2.5,
    "brutally": -2.5, "buddy": 1.5, "bug": -1.5, "bugged": -1.5, "bugging": -1.5,
    "bugs": -1.5, "bulk": 0.5, "bull": 1.5, "bullied": -2.0, "bullish": 1.5,
    "bully": -2.0, "bullying": -2.0, "bummer": -1.5, "buoyant": 1.5, "burden": -1.5,
    "burdened": -1.5, "burdening": -1.5, "burdens": -1.5, "burn": -1.5, "burned": -1.5,
    "burning": -1.5, "burns": -1.5, "bust": -2.0, "busted": -2.0, "busy": -0.5,
    "buy": 1.0, "buying": 1.0, "buys": 1.0, "calamity": -2.5, "calculated": 0.5,
    "callous": -2.0, "calm": 1.5, "calmed": 1.5, "calming": 1.5, "calms": 1.5,
    "cancel": -1.5, "cancelled": -1.5, "cancelling": -1.5, "cancels": -1.5,
    "candid": 1.5, "candidly": 1.5, "canny": 1.5, "capable": 1.5, "capably": 1.5,
    "capitalize": 1.0, "capitulate": -1.5, "capitulated": -1.5, "capitulates": -1.5,
    "captivate": 2.0, "captivated": 2.0, "captivating": 2.5, "captive": -1.5,
    "care": 1.5, "cared": 1.5, "carefree": 1.5, "careful": 1.0, "cares": 1.5,
    "caring": 2.0, "casualty": -2.0, "catastrophe": -3.0, "catastrophic": -3.0,
    "cautious": -0.5, "cave": -1.0, "cease": -0.5, "celebrate": 2.5, "celebrated": 2.5,
    "celebrates": 2.5, "celebration": 2.5, "censure": -2.0, "censure": -2.0,
    "central": 0.0, "certain": 1.0, "chagrin": -2.0, "challenge": 0.5,
    "challenged": 0.5, "challenging": 0.5, "champion": 2.0, "championed": 2.0,
    "champions": 2.0, "chance": 1.0, "change": 0.5, "changes": 0.5, "chaos": -2.5,
    "chaotic": -2.5, "charge": 0.0, "charged": -0.5, "charges": -0.5, "charitable": 1.5,
    "charity": 1.5, "charm": 2.0, "charming": 2.0, "charmingly": 2.0, "cheat": -2.5,
    "cheated": -2.5, "cheater": -2.5, "cheating": -2.5, "cheats": -2.5, "cheer": 2.0,
    "cheered": 2.0, "cheerful": 2.0, "cheerfully": 2.0, "cheering": 2.0, "cheerleader": 1.5,
    "cheers": 2.0, "cherish": 2.0, "cherished": 2.0, "cherishes": 2.0, "chief": 0.5,
    "choke": -2.0, "choked": -2.0, "chokes": -2.0, "choking": -2.0, "champion": 2.0,
    "chronic": -1.5, "chump": -1.5, "clarify": 1.0, "clarity": 1.5, "clash": -2.0,
    "clashed": -2.0, "clashes": -2.0, "clashing": -2.0, "classic": 1.5, "clean": 1.5,
    "cleaner": 1.0, "clear": 1.5, "clearer": 1.5, "clever": 1.5, "cleverly": 1.5,
    "cleverness": 1.5, "coerce": -2.0, "coerced": -2.0, "coercion": -2.0, "collapse": -2.5,
    "collapsed": -2.5, "collapses": -2.5, "collapsing": -2.5, "collateral": -1.5,
    "collective": 0.5, "collide": -1.5, "collision": -2.0, "combat": -1.5, "comedy": 1.5,
    "comfort": 1.5, "comfortable": 1.5, "comfortably": 1.5, "comforted": 1.5,
    "comforting": 1.5, "comfy": 1.5, "command": 0.5, "commend": 2.0, "commended": 2.0,
    "commit": 0.0, "commitment": 1.5, "committed": 1.0, "commodity": 0.0,
    "common": 0.0, "commonsense": 1.5, "commonwealth": 1.0, "communicate": 1.0,
    "communicated": 1.0, "communicates": 1.0, "communication": 1.0, "compact": 0.5,
    "comparable": 0.5, "compassion": 2.0, "compassionate": 2.0, "compel": 1.5,
    "compelled": 1.5, "compelling": 2.0, "compensate": 0.5, "compensated": 0.5,
    "compensation": 0.5, "compete": 0.5, "competent": 1.5, "competitive": 1.0,
    "competitively": 1.0, "complain": -2.0, "complained": -2.0, "complaining": -2.0,
    "complains": -2.0, "complaint": -2.0, "complaints": -2.0, "complement": 1.5,
    "complemented": 1.5, "complements": 1.5, "complete": 1.0, "completed": 1.0,
    "completely": 0.0, "complex": 0.0, "compliant": 0.5, "compliment": 2.0,
    "complimented": 2.0, "compliments": 2.0, "comply": 0.5, "component": 0.0,
    "composed": 0.5, "comprehend": 0.5, "compromise": -1.5, "compromised": -1.5,
    "compromises": -1.5, "compulsion": -0.5, "compulsive": -0.5, "concede": -1.5,
    "conceited": -1.5, "conceive": 1.0, "concentrate": 1.0, "concentrated": 1.0,
    "concept": 0.5, "concern": -1.5, "concerned": -1.5, "concerns": -1.5,
    "conciliatory": 1.0, "conclusive": 1.0, "concrete": 1.0, "condemn": -2.5,
    "condemned": -2.5, "condemning": -2.5, "condemns": -2.5, "condescending": -2.0,
    "condescendingly": -2.0, "condition": 0.0, "conditional": -0.5, "condone": 0.5,
    "condoned": 0.5, "condones": 0.5, "confident": 2.0, "confidently": 2.0,
    "confine": -1.5, "confined": -1.5, "confining": -1.5, "confirm": 1.0,
    "confirmed": 1.0, "confirming": 1.0, "confirms": 1.0, "conflict": -1.5,
    "conflicted": -1.5, "conflicting": -1.5, "conflicts": -1.5, "confound": -1.5,
    "confounded": -1.5, "confounding": -1.5, "confront": -1.5, "confrontation": -2.0,
    "confrontational": -2.0, "confronted": -1.5, "confronting": -1.5, "confronts": -1.5,
    "confuse": -1.5, "confused": -1.5, "confusing": -1.5, "confusion": -1.5,
    "congratulate": 2.0, "congratulation": 2.0, "congratulations": 2.5,
    "congratulatory": 2.0, "connect": 1.0, "connected": 1.0, "connecting": 1.0,
    "connection": 1.0, "connections": 1.0, "connects": 1.0, "conquer": 1.5,
    "conquered": 1.5, "conquering": 1.5, "conquers": 1.5, "conscience": 1.5,
    "conscientious": 1.5, "conscious": 1.0, "consciousness": 1.0, "consensus": 1.0,
    "consent": 1.0, "consented": 1.0, "consenting": 1.0, "consequence": -0.5,
    "consequences": -0.5, "consequently": -0.5, "conservative": -0.5,
    "considerable": 1.0, "considerably": 1.0, "considerate": 1.5,
    "consideration": 0.5, "consistency": 1.0, "consistent": 1.0,
    "consistently": 1.0, "consolidate": 1.0, "consolidated": 1.0,
    "consolidation": 1.0, "conspicuous": -0.5, "conspicuousness": -0.5,
    "conspiracy": -2.0, "conspirator": -2.0, "conspire": -2.0, "conspired": -2.0,
    "conspiring": -2.0, "constitution": 1.0, "constitutional": 1.0,
    "constrain": -1.0, "constrained": -1.0, "constraint": -1.0, "construct": 1.0,
    "constructive": 1.5, "consult": 0.5, "consultation": 0.5, "consume": -0.5,
    "consumed": -0.5, "consummate": 1.5, "contact": 0.5, "contagious": 1.0,
    "contaminate": -2.0, "contaminated": -2.0, "contaminates": -2.0, "contempt": -2.0,
    "contemptible": -2.5, "contemptuous": -2.0, "contemptuously": -2.0,
    "contend": -1.0, "contended": -1.0, "contending": -1.0, "content": 0.5,
    "contented": 0.5, "contention": -1.5, "contentious": -1.5, "contest": 0.0,
    "continue": 0.5, "continued": 0.5, "continues": 0.5, "contradict": -1.5,
    "contradicted": -1.5, "contradicting": -1.5, "contradictory": -1.5,
    "contradicts": -1.5, "contrary": -1.5, "contribute": 1.0, "contributed": 1.0,
    "contributes": 1.0, "contribution": 1.0, "contributor": 1.0, "contrive": -1.5,
    "contrived": -1.5, "controversial": -1.5, "controversy": -1.5,
    "convenient": 1.0, "conveniently": 1.0, "convince": 1.5, "convinced": 1.5,
    "convinces": 1.5, "convincing": 1.5, "convivial": 1.5, "cool": 1.5, "cooperate": 1.5,
    "cooperated": 1.5, "cooperates": 1.5, "cooperation": 1.5, "cooperative": 1.5,
    "coordinated": 1.0, "cope": 0.5, "coped": 0.5, "copes": 0.5, "copy": -0.5,
    "cordial": 1.5, "correct": 1.0, "corrected": 1.0, "correctly": 1.0, "correlation": 0.0,
    "corrode": -1.5, "corroded": -1.5, "corrodes": -1.5, "corrosion": -1.5,
    "corrosive": -2.0, "corrupt": -2.5, "corrupted": -2.5, "corrupting": -2.5,
    "corruption": -2.5, "corrupts": -2.5, "cosmetic": -0.5, "costly": -1.5,
    "courage": 2.0, "courageous": 2.5, "courageously": 2.5, "courteous": 1.5,
    "courtesy": 1.5, "courting": 1.0, "covenant": 1.0, "covet": 0.5, "coward": -2.0,
    "cowardly": -2.0, "crackdown": -2.0, "craft": 1.0, "crafted": 1.0, "crafting": 1.0,
    "crafts": 1.0, "craftsmanship": 1.5, "crash": -2.5, "crashed": -2.5, "crashes": -2.5,
    "crashing": -2.5, "craze": 0.0, "crazed": -2.0, "crazy": -2.0, "creative": 2.0,
    "creatively": 2.0, "creativity": 2.0, "credible": 1.5, "credit": 1.0,
    "credited": 1.0, "credits": 1.0, "crest": 1.0, "cripple": -2.5, "crippled": -2.5,
    "cripples": -2.5, "crippling": -2.5, "crisis": -2.5, "critic": -2.0,
    "critical": -1.5, "criticism": -2.0, "criticize": -2.0, "criticized": -2.0,
    "criticizes": -2.0, "criticizing": -2.0, "critics": -2.0, "crook": -2.5,
    "crooked": -2.5, "crude": -1.5, "crunch": -1.5, "crushed": -2.0,
    "crushes": -2.0, "crushing": -2.0, "cry": -2.0, "crying": -2.0, "culpable": -2.0,
    "cultivate": 1.0, "cultivated": 1.0, "cultivation": 1.0, "cultures": 0.5,
    "cunning": 0.5, "curb": -0.5, "cure": 2.0, "cured": 2.0, "cures": 2.0,
    "curious": 1.0, "curiously": 1.0, "curse": -2.5, "cursed": -2.5, "curses": -2.5,
    "cursing": -2.5, "curt": -1.5, "cushion": 1.0, "cut": -0.5, "cute": 1.5,
    "cuts": -0.5, "cutting": -1.0, "cynical": -1.5, "cynicism": -1.5, "damage": -2.5,
    "damaged": -2.5, "damages": -2.5, "damaging": -2.5, "damn": -2.0, "damned": -2.0,
    "damning": -2.0, "dare": 1.5, "dares": 1.5, "daring": 1.5, "daringly": 1.5,
    "dark": -1.5, "darken": -1.5, "darkened": -1.5, "darker": -1.5, "darkness": -1.5,
    "dash": -0.5, "dashing": 1.5, "daunt": -1.5, "daunted": -1.5, "daunting": -1.5,
    "dauntless": 2.0, "dawn": 1.0, "daze": -1.5, "dazed": -1.5, "dead": -2.5,
    "deadbeat": -2.0, "deadlock": -2.0, "deadly": -2.5, "deaf": -1.5, "deal": 1.0,
    "dear": 2.0, "dearly": 2.0, "death": -2.5, "debacle": -2.5, "debt": -1.5,
    "debts": -1.5, "decay": -2.0, "decayed": -2.0, "decaying": -2.0, "decays": -2.0,
    "deceit": -2.5, "deceitful": -2.5, "deceive": -2.5, "deceived": -2.5,
    "deceives": -2.5, "deceiving": -2.5, "decent": 1.5, "deception": -2.5,
    "deceptive": -2.0, "decisive": 1.5, "decisively": 1.5, "declaration": 1.0,
    "decline": -1.5, "declined": -1.5, "declines": -1.5, "declining": -1.5,
    "decrease": -1.0, "decreased": -1.0, "decreases": -1.0, "decreasing": -1.0,
    "decree": 0.0, "dedicate": 1.5, "dedicated": 1.5, "dedicates": 1.5,
    "dedication": 1.5, "deduct": -0.5, "deem": 0.5, "deemed": 0.5, "deep": 0.5,
    "deepen": 0.5, "deepened": 0.5, "deepening": 0.5, "deepens": 0.5,
    "deeper": 0.5, "deepest": 1.0, "defamation": -2.5, "defamations": -2.5,
    "defamatory": -2.0, "default": -1.5, "defaulted": -1.5, "defaulting": -1.5,
    "defaults": -1.5, "defeat": -2.0, "defeated": -2.0, "defeating": -2.0,
    "defeats": -2.0, "defect": -2.0, "defective": -2.0, "defects": -2.0,
    "defend": 1.0, "defended": 1.0, "defender": 1.0, "defending": 1.0, "defends": 1.0,
    "defer": -0.5, "deferred": -0.5, "deferring": -0.5, "defiant": -1.5,
    "defiantly": -1.5, "deficiency": -1.5, "deficient": -1.5, "deficit": -1.5,
    "define": 0.5, "definite": 1.0, "definitely": 1.0, "definitive": 1.5,
    "definitively": 1.5, "deflation": -1.0, "degrade": -2.0, "degraded": -2.0,
    "degrading": -2.0, "degradation": -2.0, "delay": -1.0, "delayed": -1.0,
    "delaying": -1.0, "delays": -1.0, "delectable": 2.5, "deliberate": -0.5,
    "deliberately": -1.0, "delicacy": 0.5, "delicate": -0.5, "delicious": 2.5,
    "delight": 2.5, "delighted": 2.5, "delightful": 2.5, "delightfully": 2.5,
    "delighting": 2.5, "delights": 2.5, "delinquency": -2.0, "delinquent": -2.0,
    "deliver": 1.5, "delivered": 1.5, "delivering": 1.5, "delivers": 1.5,
    "delusion": -1.5, "delusional": -2.0, "deluxe": 2.0, "demand": 0.5,
    "demanded": 0.5, "demanding": 0.5, "demands": 0.5, "dementia": -2.5,
    "demise": -2.0, "democrat": 0.5, "democratic": 1.0, "demolish": -2.5,
    "demolished": -2.5, "demolishes": -2.5, "demolition": -2.5, "demon": -2.5,
    "demonize": -2.5, "demonized": -2.5, "demonizes": -2.5, "demonstrates": 1.0,
    "demonstration": 0.5, "demoralize": -2.5, "demoralized": -2.5,
    "demoralizing": -2.5, "demoralizingly": -2.5, "denial": -2.0,
    "denied": -2.0, "denies": -2.0, "denounce": -2.5, "denounced": -2.5,
    "denounces": -2.5, "denouncing": -2.5, "deny": -2.0, "denying": -2.0,
    "depart": -0.5, "departed": -0.5, "departing": -0.5, "departure": -0.5,
    "depend": 0.5, "dependable": 1.5, "dependence": 0.5, "dependent": 0.5,
    "deplete": -1.5, "depleted": -1.5, "depletes": -1.5, "depleting": -1.5,
    "depletion": -1.5, "deplore": -2.5, "deplored": -2.5, "deplores": -2.5,
    "deploy": 1.0, "deployed": 1.0, "deploying": 1.0, "deploys": 1.0,
    "deport": -2.0, "deported": -2.0, "deporting": -2.0, "deports": -2.0,
    "depose": -2.0, "deposed": -2.0, "deposes": -2.0, "deposit": 0.5,
    "deposited": 0.5, "deposition": 0.0, "depraved": -2.5, "depreciate": -1.5,
    "depreciated": -1.5, "depreciates": -1.5, "depreciation": -1.5,
    "depress": -2.0, "depressed": -2.0, "depressing": -2.0, "depression": -2.5,
    "depresses": -2.0, "deprive": -2.0, "deprived": -2.0, "deprives": -2.0,
    "depriving": -2.0, "derail": -2.0, "derailed": -2.0, "derailing": -2.0,
    "derails": -2.0, "derelict": -2.0, "deride": -2.0, "derided": -2.0,
    "derides": -2.0, "deriding": -2.0, "derivative": -0.5, "derive": 0.5,
    "derived": 0.5, "derives": 0.5, "derogatory": -2.0, "descend": -1.0,
    "descending": -1.0, "descent": -1.0, "deserve": 1.5, "deserved": 1.5,
    "deserves": 1.5, "deserving": 1.5, "design": 1.0, "designated": 0.5,
    "desirable": 2.0, "desire": 1.5, "desired": 1.5, "desires": 1.5, "desiring": 1.5,
    "desolate": -2.0, "desolated": -2.0, "desolately": -2.0, "desolation": -2.5,
    "despair": -2.5, "despairing": -2.5, "despairingly": -2.5, "desperate": -2.0,
    "desperately": -2.0, "desperation": -2.0, "despicable": -2.5, "despise": -2.5,
    "despised": -2.5, "despises": -2.5, "despite": -0.5, "despondent": -2.5,
    "despondently": -2.5, "despot": -2.5, "despotic": -2.5, "destabilise": -2.5,
    "destabilize": -2.5, "destabilized": -2.5, "destabilizes": -2.5,
    "destabilizing": -2.5, "destiny": 1.0, "destitute": -2.5, "destroy": -2.5,
    "destroyed": -2.5, "destroyer": -2.5, "destroying": -2.5, "destroys": -2.5,
    "destruction": -2.5, "destructive": -2.5, "detach": -0.5, "detached": -0.5,
    "detachment": -0.5, "deter": -1.5, "deteriorate": -2.0, "deteriorated": -2.0,
    "deteriorates": -2.0, "deteriorating": -2.0, "deterioration": -2.0,
    "determination": 1.5, "determine": 1.0, "determined": 1.5, "deterrent": -1.5,
    "detract": -1.5, "detracted": -1.5, "detracting": -1.5, "detracts": -1.5,
    "detriment": -2.0, "detrimental": -2.0, "devastate": -2.5, "devastated": -2.5,
    "devastates": -2.5, "devastating": -2.5, "devastatingly": -2.5,
    "devastation": -2.5, "develop": 1.0, "developed": 1.0, "developer": 1.0,
    "developers": 1.0, "developing": 1.0, "development": 1.0, "developmental": 1.0,
    "developments": 1.0, "develops": 1.0, "device": 0.0, "devote": 1.0,
    "devoted": 1.5, "devotee": 1.5, "devotion": 1.5, "devour": -1.0,
    "devoured": -1.0, "devouring": -1.0, "devours": -1.0, "diagnose": 1.0,
    "diagnosed": 1.0, "diagnosis": 0.0, "dictator": -2.5, "dictatorial": -2.5,
    "die": -2.5, "died": -2.5, "dies": -2.5, "differ": -0.5, "difference": 0.5,
    "different": 0.0, "difficult": -1.0, "difficulties": -1.0, "difficulty": -1.0,
    "diffident": -1.5, "dig": 0.0, "dignified": 2.0, "dignify": 2.0, "dignity": 2.0,
    "digress": -1.0, "digressed": -1.0, "digresses": -1.0, "dilapidated": -2.0,
    "dilemma": -1.5, "diligence": 2.0, "diligent": 2.0, "diligently": 2.0,
    "dilute": -1.0, "diluted": -1.0, "dilutes": -1.0, "dim": -1.0, "diminish": -1.5,
    "diminished": -1.5, "diminishes": -1.5, "diminishing": -1.5, "din": -0.5,
    "dip": -0.5, "diplomacy": 1.5, "diplomatic": 1.5, "dire": -2.5, "direct": 1.0,
    "direction": 1.0, "directive": 0.5, "directly": 0.5, "disability": -2.0,
    "disable": -2.0, "disabled": -2.0, "disables": -2.0, "disabling": -2.0,
    "disadvantage": -2.0, "disadvantaged": -2.0, "disagree": -2.0, "disagreeable": -2.0,
    "disagreed": -2.0, "disagreement": -2.0, "disagrees": -2.0, "disallow": -1.5,
    "disallowed": -1.5, "disallowing": -1.5, "disallows": -1.5, "disappoint": -2.0,
    "disappointed": -2.0, "disappointing": -2.0, "disappointingly": -2.0,
    "disappointment": -2.0, "disappointments": -2.0, "disappoints": -2.0,
    "disapproval": -2.0, "disapprove": -2.0, "disapproved": -2.0, "disapproves": -2.0,
    "disapproving": -2.0, "disarm": 1.0, "disarmed": 1.0, "disarming": 1.5,
    "disarmingly": 1.5, "disarray": -2.0, "disaster": -2.5, "disastrous": -2.5,
    "disastrously": -2.5, "disavow": -1.5, "disavowed": -1.5, "disavowing": -1.5,
    "disavows": -1.5, "disbelief": -1.5, "disbelieve": -1.5, "disbelieved": -1.5,
    "disbelieves": -1.5, "discard": -1.0, "discarded": -1.0, "discarding": -1.0,
    "discards": -1.0, "discern": 1.0, "discerned": 1.0, "discerning": 1.5,
    "discharge": -0.5, "discharged": -0.5, "discharges": -0.5, "disciplinary": -1.5,
    "discipline": 0.5, "disciplined": 0.5, "disclaim": -0.5, "disclaimed": -0.5,
    "disclaims": -0.5, "disclose": 0.5, "disclosed": 0.5, "discloses": 0.5,
    "disclosure": 0.5, "discomfort": -1.5, "disconnect": -1.0,
    "disconnected": -1.0, "disconnecting": -1.0, "disconnects": -1.0,
    "discontent": -1.5, "discontented": -1.5, "discontinue": -1.0,
    "discontinued": -1.0, "discontinues": -1.0, "discord": -1.5,
    "discordance": -1.5, "discordant": -1.5, "discount": -0.5, "discounted": -0.5,
    "discounting": -0.5, "discounts": -0.5, "discourage": -2.0,
    "discouraged": -2.0, "discouragement": -2.0, "discourages": -2.0,
    "discouraging": -2.0, "discourteous": -1.5, "discourteously": -1.5,
    "discover": 1.0, "discovered": 1.0, "discovers": 1.0, "discovery": 1.5,
    "discredit": -2.0, "discredited": -2.0, "discrediting": -2.0,
    "discredits": -2.0, "discreet": 1.0, "discreetly": 1.0, "discrepancy": -1.0,
    "discretion": 0.5, "discriminate": -2.5, "discriminated": -2.5,
    "discriminates": -2.5, "discriminating": -1.0, "discrimination": -2.5,
    "discriminatory": -2.5, "discuss": 1.0, "discussed": 1.0, "discusses": 1.0,
    "discussion": 1.0, "disdain": -2.0, "disdained": -2.0, "disdaining": -2.0,
    "disdains": -2.0, "disease": -2.0, "diseased": -2.0, "diseases": -2.0,
    "disenchant": -2.0, "disenchanted": -2.0, "disenchanting": -2.0,
    "disenchantment": -2.0, "disenfranchise": -2.5, "disenfranchised": -2.5,
    "disengage": -1.5, "disengaged": -1.5, "disengagement": -1.5,
    "disengagements": -1.5, "disengages": -1.5, "disgrace": -2.5,
    "disgraced": -2.5, "disgraceful": -2.5, "disgracefully": -2.5,
    "disgruntle": -2.0, "disgruntled": -2.0, "disgust": -2.5, "disgusted": -2.5,
    "disgusting": -2.5, "disgustingly": -2.5, "dishearten": -2.0,
    "disheartened": -2.0, "disheartening": -2.0, "dishearteningly": -2.0,
    "disheveled": -1.5, "dishonest": -2.5, "dishonestly": -2.5,
    "dishonesty": -2.5, "dishonor": -2.5, "dishonorable": -2.5,
    "dishonored": -2.5, "dishonoring": -2.5, "dishonors": -2.5,
    "disillusion": -2.0, "disillusioned": -2.0, "disillusioning": -2.0,
    "disillusionment": -2.0, "disincentive": -1.5,
    "disinclined": -0.5, "disingenuous": -1.5,
    "disingenuously": -1.5, "disintegrate": -2.5,
    "disintegrated": -2.5, "disintegrates": -2.5,
    "disintegration": -2.5,
    "disinterest": -1.5, "disinterested": -1.5,
    "dislike": -2.0, "disliked": -2.0, "dislikes": -2.0,
    "dislocated": -1.5, "dislodge": -1.5,
    "dislodged": -1.5, "disloyal": -2.5,
    "disloyalty": -2.5, "dismal": -2.5, "dismally": -2.5,
    "dismantle": -1.0, "dismantled": -1.0,
    "dismantling": -1.0, "dismay": -2.0, "dismayed": -2.0,
    "dismaying": -2.0, "dismayingly": -2.0,
    "dismiss": -1.5, "dismissed": -1.5,
    "dismisses": -1.5, "dismissing": -1.5,
    "dismissive": -2.0, "disobedience": -2.0,
    "disobedient": -2.0, "disobey": -2.0,
    "disobeyed": -2.0, "disobeying": -2.0,
    "disobeys": -2.0, "disorder": -2.0,
    "disordered": -2.0, "disorderly": -2.0,
    "disorganised": -2.0, "disorganized": -2.0,
    "disorient": -1.5, "disoriented": -1.5,
    "disown": -1.5, "disowned": -1.5,
    "disowning": -1.5, "disowns": -1.5,
    "disparage": -2.0, "disparaged": -2.0,
    "disparages": -2.0, "disparaging": -2.0,
    "disparagingly": -2.0, "disparity": -1.5,
    "dispel": 1.0, "dispensable": -1.5,
    "dispense": 0.5, "dispensed": 0.5,
    "disperse": -0.5, "dispersal": -0.5,
    "displace": -1.5, "displaced": -1.5,
    "displaces": -1.5, "displacement": -1.5,
    "display": 0.5, "displease": -2.0,
    "displeased": -2.0, "displeasing": -2.0,
    "displeasure": -2.0, "disposable": 0.0,
    "dispose": 0.5, "disposed": 0.5,
    "disposition": 0.5, "dispossess": -2.0,
    "dispossessed": -2.0, "dispossesses": -2.0,
    "disproportionate": -1.5,
    "disproportionately": -1.5,
    "disprove": -1.0, "disproved": -1.0,
    "disproves": -1.0, "disputable": -1.0,
    "dispute": -1.5, "disputed": -1.5,
    "disputes": -1.5, "disputing": -1.5,
    "disqualify": -2.0, "disqualified": -2.0,
    "disqualifies": -2.0, "disqualifying": -2.0,
    "disregard": -1.5, "disregarded": -1.5,
    "disregarding": -1.5, "disregards": -1.5,
    "disrepute": -2.5, "disrespect": -2.0,
    "disrespected": -2.0, "disrespectful": -2.0,
    "disrespectfully": -2.0, "disrespects": -2.0,
    "disrupt": -2.0, "disrupted": -2.0,
    "disrupting": -2.0, "disruption": -2.0,
    "disruptions": -2.0, "disruptive": -2.0,
    "disrupts": -2.0, "dissatisfaction": -2.0,
    "dissatisfactory": -2.0, "dissatisfied": -2.0,
    "dissatisfies": -2.0, "dissatisfy": -2.0,
    "dissatisfying": -2.0, "dissemble": -1.5,
    "dissembled": -1.5, "dissembles": -1.5,
    "disseminate": 1.0, "disseminated": 1.0,
    "disseminates": 1.0, "dissension": -2.0,
    "dissensions": -2.0, "dissent": -2.0,
    "dissenter": -2.0, "dissenting": -2.0,
    "dissertation": 0.5, "disservice": -2.0,
    "dissidence": -2.0, "dissident": -2.0,
    "dissidents": -2.0, "dissolve": -0.5,
    "dissolved": -0.5, "dissolves": -0.5,
    "dissonance": -1.5, "dissonant": -1.5,
    "dissuade": -1.5, "dissuaded": -1.5,
    "dissuades": -1.5, "distance": -0.5,
    "distanced": -0.5, "distant": -0.5,
    "distaste": -2.0, "distasteful": -2.0,
    "distinct": 1.0, "distinction": 1.0,
    "distinctive": 1.5, "distinctly": 1.0,
    "distinguish": 1.0, "distinguished": 1.5,
    "distinguishes": 1.0, "distort": -1.5,
    "distorted": -1.5, "distorting": -1.5,
    "distorts": -1.5, "distract": -1.5,
    "distracted": -1.5, "distracting": -1.5,
    "distraction": -1.5, "distracts": -1.5,
    "distraught": -2.5, "distress": -2.5,
    "distressed": -2.5, "distresses": -2.5,
    "distressing": -2.5, "distressingly": -2.5,
    "distribute": 1.0, "distributed": 1.0,
    "distribution": 1.0, "distributor": 1.0,
    "distrust": -2.5, "distrusted": -2.5,
    "distrustful": -2.0, "distrusting": -2.5,
    "distrusts": -2.5, "disturb": -2.0,
    "disturbance": -2.0, "disturbed": -2.0,
    "disturbing": -2.0, "disturbingly": -2.0,
    "disturbs": -2.0, "diverge": -1.0,
    "diverged": -1.0, "divergence": -1.0,
    "divergent": -1.0, "diverges": -1.0,
    "diverse": 1.5, "diversification": 1.5,
    "diversified": 1.5, "diversify": 1.5,
    "diversion": -0.5, "diversity": 1.5,
    "divert": -0.5, "diverted": -0.5,
    "diverting": -0.5, "diverts": -0.5,
    "dividend": 1.0, "divine": 2.5,
    "divinely": 2.0, "division": -0.5,
    "divisive": -2.0, "divorce": -2.5,
    "divorced": -2.5, "divorces": -2.5,
    "divorcing": -2.5, "dizziness": -1.0,
    "dizzy": -1.0, "docile": 0.0,
    "dock": -0.5, "docked": -0.5,
    "docks": -0.5, "doctrine": 0.5,
    "document": 0.5, "documented": 0.5,
    "dodge": -0.5, "dodged": -0.5,
    "dodges": -0.5, "dodging": -0.5,
    "dogged": 0.5, "doggedly": 0.5,
    "doldrums": -2.0, "domain": 0.0,
    "domestic": 0.5, "dominance": 1.5,
    "dominant": 1.5, "dominate": 0.0,
    "dominated": 0.0, "dominates": 0.0,
    "dominating": 0.0, "domination": 0.0,
    "donate": 2.0, "donated": 2.0,
    "donates": 2.0, "donating": 2.0,
    "donation": 1.5, "donations": 1.5,
    "doom": -2.5, "doomed": -2.5,
    "doomsday": -2.5, "dormant": -1.0,
    "dose": 0.0, "doubt": -2.0,
    "doubted": -2.0, "doubtful": -2.0,
    "doubting": -2.0, "doubts": -2.0,
    "doubtfully": -1.5, "dour": -2.0,
    "downgrade": -2.0, "downgraded": -2.0,
    "downgrades": -2.0, "download": 0.5,
    "downplay": -1.0, "downplayed": -1.0,
    "downplaying": -1.0, "downplays": -1.0,
    "downright": -1.5, "downside": -1.0,
    "downsize": -1.5, "downsized": -1.5,
    "downsizing": -1.5, "downturn": -2.0,
    "draft": 0.5, "draconian": -2.5,
    "draconic": -2.5, "drain": -1.5,
    "drained": -1.5, "draining": -1.5,
    "drains": -1.5, "drastic": -1.5,
    "drastically": -1.5, "draught": -0.5,
    "drawback": -1.5, "drawbacks": -1.5,
    "dread": -2.5, "dreaded": -2.5,
    "dreadful": -2.5, "dreadfully": -2.5,
    "dreading": -2.5, "dream": 1.5,
    "dreams": 1.5, "dreamy": 1.5,
    "dreary": -1.5, "drench": -1.5,
    "drenched": -1.5, "drenching": -1.5,
    "drift": -0.5, "drifted": -0.5,
    "drifting": -0.5, "drifts": -0.5,
    "drive": 1.5, "driven": 1.5,
    "driving": 1.0, "drones": -0.5,
    "droop": -1.0, "drooped": -1.0,
    "drooping": -1.0, "droops": -1.0,
    "drop": -1.0, "dropped": -1.0,
    "drops": -1.0, "drought": -2.0,
    "drown": -2.5, "drowned": -2.5,
    "drowning": -2.5, "drowsy": -0.5,
    "drudgery": -2.0, "dubious": -1.5,
    "dud": -1.5, "dull": -1.5,
    "dullard": -1.5, "dumb": -2.0,
    "dumbfound": -2.0, "dumbfounded": -2.0,
    "dumbfounding": -2.0, "dump": -1.5,
    "dumped": -1.5, "dumping": -1.5,
    "dumps": -1.5, "dupe": -2.0,
    "duped": -2.0, "duplicitous": -2.5,
    "durability": 1.5, "durable": 1.5,
    "dusk": 0.0, "dutiful": 1.5,
    "dutifully": 1.5, "duty": 1.0,
    "dwindle": -1.5, "dwindled": -1.5,
    "dwindling": -1.5, "dynamic": 1.5,
    "dysfunction": -2.0, "dysfunctional": -2.0,
    "eager": 1.5, "eagerly": 1.5,
    "eagerness": 1.5, "early": 0.5,
    "earn": 2.0, "earned": 2.0,
    "earnest": 1.5, "earnestly": 1.5,
    "earnestness": 1.5, "earning": 2.0,
    "earnings": 2.0, "earns": 2.0,
    "ease": 1.5, "eased": 1.5,
    "eases": 1.5, "easier": 1.5,
    "easiest": 1.5, "easily": 1.5,
    "easiness": 1.5, "easing": 1.5,
    "easy": 1.5, "easygoing": 1.5,
    "ebullience": 2.0, "ebullient": 2.0,
    "eccentric": 0.5, "eccentricity": 0.5,
    "echo": 0.0, "eclectic": 1.0,
    "eclipse": -0.5, "economic": 0.5,
    "economical": 1.5, "economically": 0.5,
    "economies": 0.5, "economize": 1.5,
    "economy": 0.5, "ecstasy": 2.5,
    "ecstatic": 2.5, "ecstatically": 2.5,
    "edge": 0.5, "edgy": -0.5,
    "educable": 1.5, "educate": 1.5,
    "educated": 1.5, "education": 1.5,
    "educational": 1.5, "educative": 1.5,
    "educator": 1.5, "eerie": -1.5,
    "eerily": -1.5, "effective": 1.5,
    "effectively": 1.5, "effectiveness": 1.5,
    "effectual": 1.5, "efficacious": 1.5,
    "efficiency": 1.5, "efficient": 1.5,
    "efficiently": 1.5, "effort": 1.0,
    "effortless": 1.5, "effortlessly": 1.5,
    "effusion": 1.0, "effusive": 1.5,
    "effusively": 1.5, "effusiveness": 1.5,
    "egalitarian": 1.5, "ego": -0.5,
    "egocentric": -1.5, "egomania": -2.0,
    "egotism": -2.0, "egotistical": -2.0,
    "egregious": -2.5, "egregiously": -2.5,
    "eject": -1.5, "ejected": -1.5,
    "ejecting": -1.5, "ejects": -1.5,
    "elaborate": 1.0, "elaborated": 1.0,
    "elaborately": 1.0, "elaboration": 0.0,
    "elapse": -1.0, "elastic": 1.0,
    "elated": 2.5, "elation": 2.5,
    "electrify": 2.0, "elegance": 2.0,
    "elegant": 2.0, "elegantly": 2.0,
    "element": 0.0, "elevate": 1.5,
    "elevated": 1.5, "elevates": 1.5,
    "elevation": 1.5, "elicit": 1.0,
    "elicited": 1.0, "eliciting": 1.0,
    "elicits": 1.0, "eligible": 1.0,
    "eliminate": -1.0, "eliminated": -1.0,
    "eliminates": -1.0, "elimination": -1.0,
    "elite": 1.5, "elitism": -1.0,
    "elitist": -1.0, "eloquence": 2.0,
    "eloquent": 2.0, "eloquently": 2.0,
    "elusive": -1.0, "emaciated": -2.0,
    "emancipate": 2.0, "emancipated": 2.0,
    "emancipates": 2.0, "emancipation": 2.0,
    "embargo": -2.0, "embark": 1.0,
    "embarked": 1.0, "embarking": 1.0,
    "embarks": 1.0, "embarrass": -2.0,
    "embarrassed": -2.0, "embarrassing": -2.0,
    "embarrassingly": -2.0, "embarrassment": -2.0,
    "embattled": -2.0, "embellish": 1.0,
    "embellished": 1.0, "embellishing": 1.0,
    "embellishment": 1.0, "embezzle": -3.0,
    "embezzled": -3.0, "embezzlement": -3.0,
    "embezzler": -3.0, "embitter": -2.0,
    "embittered": -2.0, "embittering": -2.0,
    "embitters": -2.0, "emblem": 1.0,
    "emblematic": 1.0, "embodiment": 1.5,
    "embolden": 1.5, "emboldened": 1.5,
    "emboldening": 1.5, "emboldens": 1.5,
    "embrace": 2.0, "embraced": 2.0,
    "embraces": 2.0, "embracing": 2.0,
    "embroil": -1.5, "embroiled": -1.5,
    "embroiling": -1.5, "embroils": -1.5,
    "emerge": 1.0, "emerged": 1.0,
    "emergence": 1.0, "emergent": 1.0,
    "emerges": 1.0, "emerging": 1.0,
    "emission": -0.5, "emit": 0.0,
    "emitted": 0.0, "emitting": 0.0,
    "emotion": 0.5, "emotional": 0.0,
    "emotionally": 0.0, "emotive": 1.0,
    "empathic": 2.0, "empathize": 2.0,
    "empathy": 2.0, "emperor": 1.0,
    "emphasise": 1.0, "emphasize": 1.0,
    "emphasized": 1.0, "emphasizes": 1.0,
    "emphatic": 1.5, "emphatically": 1.5,
    "empire": 0.5, "empirical": 0.5,
    "employ": 0.5, "employed": 0.5,
    "employee": 0.5, "employer": 0.5,
    "employment": 0.5, "empower": 2.5,
    "empowered": 2.5, "empowering": 2.5,
    "empowerment": 2.5, "empowers": 2.5,
    "emptiness": -1.5, "empty": -1.0,
    "enable": 1.5, "enabled": 1.5,
    "enables": 1.5, "enabling": 1.5,
    "enact": 0.5, "enacted": 0.5,
    "enacting": 0.5, "enacts": 0.5,
    "enchant": 2.0, "enchanted": 2.0,
    "enchanting": 2.5, "enchantingly": 2.5,
    "enchantment": 2.0, "enchantress": 2.5,
    "encourage": 2.0, "encouraged": 2.0,
    "encouragement": 2.0, "encourages": 2.0,
    "encouraging": 2.0, "encouragingly": 2.0,
}

BOOSTER_WORDS: dict[str, float] = {
    "very": 0.293, "extremely": 0.293, "highly": 0.293,
    "remarkably": 0.293, "exceptionally": 0.293, "incredibly": 0.293,
    "absolutely": 0.293, "completely": 0.293, "totally": 0.293,
    "deeply": 0.293, "truly": 0.293, "barely": -0.293,
    "hardly": -0.293, "somewhat": -0.293, "slightly": -0.293,
    "marginally": -0.293,
}

NEGATION_WORDS: set[str] = {
    "not", "no", "never", "neither", "nor", "nothing", "nowhere",
    "hardly", "barely", "scarcely", "doesn't", "don't", "didn't",
    "won't", "wouldn't", "couldn't", "shouldn't", "isn't", "aren't",
    "wasn't", "weren't", "haven't", "hasn't", "hadn't", "can't",
    "cannot", "mustn't", "needn't", "daren't",
}


def _tokenize(text: str) -> list[str]:
    """
    Convert the input text to lowercase, remove punctuation and numbers,
    split into words, and return only words longer than 1 character.
    """
    # --- YOUR CODE HERE ---
    pass


def _is_negated(tokens: list[str], idx: int, window: int = 3) -> bool:
    """
    Check if the word at position `idx` in `tokens` is negated by
    looking back up to `window` positions for a negation word.
    Return True if a negation word is found within range.
    """
    # --- YOUR CODE HERE ---
    pass


def score_headline(headline: str) -> dict:
    """
    Score a single headline using the VADER lexicon approach.
    Tokenize the headline, look up each token in the lexicon,
    apply negation and booster adjustments, then compute the
    compound score using the normalization formula:
        compound = sum_scores / sqrt(sum_scores^2 + 15)
    Return a dict with 'compound', 'pos', 'neg', and 'neu' scores.
    """
    # --- YOUR CODE HERE ---
    pass


def analyze_ticker_sentiment(ticker: str, limit: int = 10) -> dict:
    """
    Fetch news articles for the ticker, score each headline,
    and aggregate the results.
    Return a dict with:
      - ticker, articles_count
      - overall_sentiment (BULLISH / BEARISH / NEUTRAL based on avg compound)
      - average_compound, positive_articles, negative_articles, neutral_articles
      - articles list with title, publisher, sentiment, label, pos, neg, neu
    """
    # --- YOUR CODE HERE ---
    pass


def _fetch_news_for_sentiment(ticker: str, limit: int) -> list[dict]:
    """
    Helper that calls dc.get_ticker_news(ticker, limit).
    Import data_client from the parent package.
    """
    from .. import data_client as dc
    return dc.get_ticker_news(ticker, limit)


def _sentiment_label(compound: float) -> str:
    """
    Convert a compound score to a human-readable label.
    >= 0.35 → "BULLISH"
    >= 0.1  → "SLIGHTLY BULLISH"
    <= -0.35 → "BEARISH"
    <= -0.1 → "SLIGHTLY BEARISH"
    Otherwise → "NEUTRAL"
    """
    # --- YOUR CODE HERE ---
    pass
